### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by zalexua** [peci1/more-snooze#6]
I downloaded tb78 branch sources as zip, renamed to .xpi, tried to install Addon from file.
But I get error that it appears to be corrupt.

What I did wrong?

TB 78.11.0

**Comment by jameshibbard** [comment]
I would imagine that it is because the `xpi` file needs the manifest file at its root. The downloaded zip however contains a `more-snooze-tb78` folder which in turn contains the manifest file.

What you could do is download the zip, extract it, change into the newly created folder and zip everything up again:

```bash
zip -r more-snooze-tb78.xpi *
```

Or, just download the latest release as an xpi: https://github.com/peci1/more-snooze/releases/tag/v3.0.0

Either will work :)

**Comment by zalexua** [comment]
That was a little stupid .... I did not spot that ....
When I downloaded sources as ZIP here, it puts all files into subfolder with name of repo-branch/tag.
I needed to extract it and compress again without the subfolder.
p.s. renaming to .xpi is not needed, TB accepts .zip without issues.

**Comment by jameshibbard** [comment]
Glad you got it working.
